# Generated by Django 4.1.7 on 2023-04-05 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_uploadedingredient_alter_ingredient_ingredient"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="grams",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="instruction",
            name="num",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
